puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title=StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    submit=SubmitField('post')
    

puppycompanyblog/blog_posts/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

#create

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data,text=form.text.data,user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog post created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html',form=form)

#view
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,date=blog_post.date,post=blog_post)

#update
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)
    
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('blog post created')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
    elif request.method =='GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html',title='Updating',form=form)

#delete
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog post deleted')
    return redirect(url_for('core.index')) 

puppycompanyblog/core/views.py
from flask import Blueprint,render_template,redirect,request
from puppycompanyblog.models import BlogPost
core = Blueprint('core',__name__)

@core.route('/')
def index():
    page=request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

puppycompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from puppycompanyblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from puppycompanyblog.models import User, BlogPost
from puppycompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            #Log in the user
            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
        else:
            flash("already logged in ")
    
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        # print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=4)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

puppycompanyblog/templates/account.html
 {% extends 'base.html' %}


{% block content %}

<div class='jumbotron'>
    <div align = 'center'>

        <h1> welocme to the page of {{current_user.username}}</h1>
        <img align='center' src='{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}'>

    </div>
</div>

<div class='container'>
    <form method='POST' enctype='multipart/form-data'>

    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email()}}<br>
    {{form.username.label}}{{form.username()}}<br>
    {{form.picture.label}}{{form.picture()}}<br>
    {{form.submit()}}

    </form>
</div>

{% endblock %} 

puppycompanyblog/templates/base.html
 <!doctype html>
<html lang="en">


  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

  </head>



  <body>

    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('core.info')}}">Aboutus</a>
        </li>

       {% if current_user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.account')}}" >Account</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{url_for('blog_posts.create_post')}}" >CreatePost</a>
        </li>

        {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}" >Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.register')}}" >Register</a>
          </li>
          {% endif  %}
      </ul>
   

        <div class='container'>

            {% block content %}

            {% endblock %}

        </div>



   
    
  </body>
</html> 

puppycompanyblog/templates/blog_post.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
   <h1>{{post.title}}</h1>
    <h2>written by:{{post.author.username}}</h2>
    <h3>published: {{post.date.strftime('%B %d,%Y')}}</h3>
     <p>{{post.text}}</p>
     {% if post.author == current_user %}

       <div>
        <a href='{{url_for('blog_posts.update',blog_post_id=post.id)}}'>update</a>
        <a href='{{url_for('blog_posts.delete',blog_post_id=post.id)}}'>delete</a>
       </div>

     {% endif %}


{% endblock %} 

puppycompanyblog/templates/create_post.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <form class='form-group' method='POST'>
    
        {{form.hidden_tag()}}

        <div class='form-group'>
        {{form.title.label(class='form-control-label')}}
        {{form.title(class='form-control form-control-lg')}}
        </div>

        <div class='form-group'>
            {{form.text.label(class='form-control-label')}}
            {{form.text(class='form-control form-control-lg')}}
        </div>
        
        <div class='form-group'>
            {{form.submit(class='btn btn-outline-info')}}
        </div>

    </form>


</div>

{% endblock %} 

puppycompanyblog/templates/ex.html
<ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link " aria-current="page" href="{{url_for('core.index')}}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="{{url_for('core.info')}}">About Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="#">Logout</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="#">Account</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="#">CreatePost</a>
    </li>



    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="#">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" ria-current="page" href="#">Register</a>
    </li>
  </ul>


</div>
{% comment %} 
<div class="modal" tabindex="-1" role='dialog' id='del_modal'>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete post ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are you sure to delete ? </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>

          <form action='{{url_for('blog_posts.delete',blog_post_id=post.id)}}' method='post'>
          <inputclass="btn btn-primary"  type="submit" value='Delete' >
          </form>

        </div>

      </div>
    </div>
  </div> {% endcomment %}

        {% comment %} <button type='button' class='btn btn-danger' data-toggle ='modal' data-target='#del_modal'>Delete</button> {% endcomment %}

puppycompanyblog/templates/index.html
{% extends "base.html" %}

{% block content %}

  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
    <p>Welcome to Our Company's Blog Page</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>

{% endblock %}

puppycompanyblog/templates/info.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <h1>Info about Puppy comapny blog</h1>
    
    <p> My Bonnie lies over the ocean.

        My Bonnie lies over the sea.
      
        My Bonnie lies over the ocean.
      
        Oh, bring back my Bonnie to me.
    </p>
</div>

{% endblock %}

puppycompanyblog/templates/login.html
{% extends 'base.html' %}


{% block content %}

<form method='POST'>
    
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email()}}<br>
    {{form.password.label}}{{form.password()}}<br>
    {{form.submit()}}

</form>

{% endblock %}

puppycompanyblog/templates/register.html
{% extends 'base.html' %}


{% block content %}

<form method='POST'>
    
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email()}}<br>
    {{form.username.label}}{{form.username()}}<br>
    {{form.password.label}}{{form.password()}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm()}}<br>
    {{form.submit()}}

</form>

{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
 {% extends 'base.html' %}


{% block content %}

<div class='container'>
    <div class='jumbotron'>
        <div align='center'>
            <h1> welocme to the page for {{user.username}}</h1>
            <img src='{{url_for('static',filename='profile_pics/'+user.profile_image)}}'>
        </div>
    </div>


{% for post in blog_posts.items %}
<h2> <a href='{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}'>{{post.title}}</a></h2>
written by: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
<p class='text-muted'>published on:{{post.date.strftime("%Y-%m-%d")}}</p>
<br>
<p>{{post.text}}</P>
<br> 

{% endfor %}

</div>

<nav aria-label="Page navigation example" >
    <ul class='pagination justify-content-center'>
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
            <a class='page-link' href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"> {{page_num}}</a>
        </li>
        {% else %}
        <!-- <li class='page-item disabled'> -->
            <li class="page-item"><a class='page-link' href="{{url_for('users.user_posts',username=user.username,page=page_num)}}"> {{page_num}}</a></li>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}  -->